vm:
    mu_v: 1
    window: 3
    alpha_v: 1
sc:
    mu_s: 2
    alpha_s: 2
zipf:
    zipf_alphas:
      - 1.1
      - 1.5
      - 2
      - 2.5
      - 3
    max_job_size: 50
    jobs_to_generate: 3600
    job_sizes_to_generate: 4000
    val_lambda: 2
    num_intervals: 60
uniform:
    min_job_size: 1
    max_job_size: 5
    jobs_to_generate: 3600
other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes