vm:
    mu_v: 1
    window: 3
    alpha_v: 1
sc:
    mu_s: 2
    alpha_s: 2
other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes